create table if not exists public.admin_users (
  user_id uuid primary key references auth.users (id) on delete cascade
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  product jsonb not null,
  is_published boolean not null default true
);

alter table public.admin_users enable row level security;
alter table public.products enable row level security;

create or replace function public.is_catalog_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users
    where user_id = (select auth.uid())
  );
$$;

revoke all on function public.is_catalog_admin() from public;
grant execute on function public.is_catalog_admin() to anon, authenticated;

drop policy if exists "Admins can verify their own access" on public.admin_users;
create policy "Admins can verify their own access"
on public.admin_users
for select
to authenticated
using (user_id = (select auth.uid()));

drop policy if exists "Visitors can read published products" on public.products;
create policy "Visitors can read published products"
on public.products
for select
to anon, authenticated
using (is_published or (select public.is_catalog_admin()));

drop policy if exists "Admins can add products" on public.products;
create policy "Admins can add products"
on public.products
for insert
to authenticated
with check ((select public.is_catalog_admin()));

drop policy if exists "Admins can edit products" on public.products;
create policy "Admins can edit products"
on public.products
for update
to authenticated
using ((select public.is_catalog_admin()))
with check ((select public.is_catalog_admin()));

drop policy if exists "Admins can delete products" on public.products;
create policy "Admins can delete products"
on public.products
for delete
to authenticated
using ((select public.is_catalog_admin()));

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "Admins can upload product images" on storage.objects;
create policy "Admins can upload product images"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'product-images'
  and (select public.is_catalog_admin())
);

drop policy if exists "Admins can update product images" on storage.objects;
create policy "Admins can update product images"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'product-images'
  and (select public.is_catalog_admin())
)
with check (
  bucket_id = 'product-images'
  and (select public.is_catalog_admin())
);

drop policy if exists "Admins can delete product images" on storage.objects;
create policy "Admins can delete product images"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'product-images'
  and (select public.is_catalog_admin())
);

-- After creating the owner account in Supabase Auth, allowlist its user UUID:
-- insert into public.admin_users (user_id) values ('PASTE-AUTH-USER-UUID-HERE');
